### ISSUE TITLE
Need B-Tax/CCC testing

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/B-Tax#103]
To verify that Tax-Calculator and TaxBrain runs get the same answer for the same input, a set of scripts are maintained in the Tax-Calculator repo:

https://github.com/open-source-economics/Tax-Calculator/tree/master/taxcalc/taxbrain

These tests run a selected set of reforms on both Tax-Calculator and TaxBrain and then compare the results. The TaxBrain jobs are run programmatically by using the `selenium` and `chromedriver` tools to actually interact with the browser.

We should have a similar set of scripts for B-Tax and CCC to make sure that the same inputs to CCC and B-Tax get the same results.

**Comment by PeterDSteinberg** [comment]
The link above is broken, but I think we do have a need for browser-based automated testing of the various Taxbrain features - mainly for diagnostics after deployment.  @brittainhard do you have experience with Selenium or other browser UI testing frameworks? (I don't)  

cc @MattHJensen

**Comment by hdoupe** [comment]
I don't think so. I don't see us doing any front-end testing in the foreseeable future.

**Comment by jdebacker** [comment]
Ok - thanks @hdoupe.  Will close this issue.
