### ISSUE TITLE
B-Tax util for METTR bubble plot

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/B-Tax#106]
It would be handy for B-Tax users to be able to generate static METTR bubble plots like [ this interactive one](http://www.ospc.org/gallery/embed/corp_mettr/) for any 2 calculators representing baseline and reform. 

![image](https://cloud.githubusercontent.com/assets/8301092/19398259/c88d1632-9219-11e6-9626-ca48009063f7.png)

It would be best to offer both horizontal and portrait layouts.

**Comment by jdebacker** [comment]
Closing this as it's been replaced by Issue #138.
