### ISSUE TITLE
Fix issue related to setting on pandas DataFrame copy

### ISSUE THREAD

**Issue by PeterDSteinberg** [open-source-economics/B-Tax#112]
I saw this in the celery logs just now:

```
[2016-10-24 14:37:57,320: WARNING/MainProcess] /Users/psteinberg/Documents/AEI/jdebacker_btax/btax/pull_soi_proprietorship.py:162: SettingWithCopyWarning:

```

This can mean in some cases that the assignment does not take place.  Use copy somewhere.

**Comment by jdebacker** [comment]
@PeterDSteinberg - are you running from the current master?  I'm not getting this on my machine.

**Comment by PeterDSteinberg** [comment]
@jdebacker I'm not seeing this error anymore when trying to replicate it.  I'll close this issue in a couple days if I don't see it again.  I think you are right about not being on correct branch because the quoted error has a line number that doesn't make sense relative to code in master and my PR #113.

**Comment by jdebacker** [comment]
This issue has been fixed (not sure of PR).
