### ISSUE TITLE
Update instructions to get B-Tax running on others' machines

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/B-Tax#126]
The current readme file is not complete.  When following the current instructions, the user will fail to be able to run B-Tax for at least three reasons:

1) Dependency upon Tax-Calculator.
2) Dependency upon the SOI PUF. 
3) They main not be running the correct version of Python.

This leaves a few questions:
a) How should we handle the PUF dependency?  We probably want to do what is done with Tax Calculator for users without the PUF.
b) Can we have B-Tax set up so that the PUF (or its replacement) only needs to reside in the TaxCalc directory (and not also in the B-Tax directory)?
c) Can we create a Conda environment and provide users instructions to invoke the environment (as we do for Tax-Calc?)?
d) At what point do we switch to Python 3.x?

cc @MattHJensen @PeterDSteinberg

**Comment by jdebacker** [comment]
@MattHJensen is this something you want addressed ASAP for the marketing push?

**Comment by MattHJensen** [comment]
@jdebacker, the first wave of marketing is going to focus on the webapps, so I didn't include this [here](https://github.com/OpenSourcePolicyCenter/webapp-public/issues/493).

**Comment by PeterDSteinberg** [comment]
PR #143 adds Python 3 support.  Only a few minor changes were needed.  

Ideally the workflow should be that we / I maintain conda packages up-to-date enough to where a user of any of these repos can do:

```
conda create --python 3.5 -c ospc btax taxcalc ogusa
```
and be all set to run B-Tax, Tax-Calculator, and OG-USA in interactive Python usage.  The work on policybrain-builder repo for building conda packages has been helpful (it builds and pushes these three repos' pkgs to anaconda.org/ospc).  The README for policybrain-builder is [here](https://github.com/open-source-economics/policybrain-builder) I'm happy to show others how to use it more.

**Comment by jdebacker** [comment]
This issues has been addressed with PR #210
