### ISSUE TITLE
Review all uses of `.ix` in favor of `.loc` or `.iloc`

### ISSUE THREAD

**Issue by PeterDSteinberg** [open-source-economics/B-Tax#147]
I saw at least one usage of `.ix` in B-Tax.  Reminder for me to fix it.  `.loc` is index lookup, `.iloc` is positional slicing.  `.ix` guesses between those two options, sometimes guessing wrong, so I think it is better to avoid `.ix`.

**Comment by jdebacker** [comment]
This has been addressed in PR #189
