### ISSUE TITLE
Results for debt financed investments

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/B-Tax#158]
@codykallen noticed a change in output since an B-Tax run in October, namely that the debt-financed METTRs for corporate and non-corporate investment has gone up by about 7 and 12 percentage points, respectively.

This does not appear to have to do with the addition of intellectual property assets in the calculations.

This issue is to explore why these changes are present and whether they are valid.

**Comment by codykallen** [comment]
After further investigation, I believe at least part of the change can actually be attributed to the higher EMTR on interest income from tax-calculator. About a month or two ago, Anderson Frailey (at my request) redid the weights in the puf to fix the distribution of taxable interest, which was underestimating by over 50% the amount of interest income for those with AGI over $1 million. That alone substantially raised the weighted average EMTR on interest income that goes into calculating the EMTR on debt-funded investment.
 
It seems like this could explain at least part of the directional shift in the EMTRs on debt-funded investment, but not why the percentage point change was twice as large for non-corporate investment than for corporate investment.

**Comment by jdebacker** [comment]
Good find, Cody.  It appears to be a result of those changes to Tax-Calc.  The October runs found an EMTR on interest income of about 28%.  Runs with new Tax-Calc yield an EMTR of about 35%.  That accounts for the difference (you can test by hard coding in the lower EMTR for interest income into B-Tax).   

The percentage point differences in the effect of this vary between the corporate and non-corporate sector because the taxes (and expected after tax returns) differ between these two entities.

I'll leave open for you to confirm this seems ok.  But running B-Tax with no bonus, I find `mettr_c_d = -0.014` and `mettr_nc_d=0.23`.  When I hard code (in `btax.parameters.py`) `tau_int=0.24` and do the same run, I find  `mettr_c_d = -0.140` and `mettr_nc_d=0.044`

**Comment by codykallen** [comment]
@jdebacker, thanks for following up on this. That makes sense to me.

**Comment by jdebacker** [comment]
Thanks for confirming.  Closing this issue.
