### ISSUE TITLE
tax CG and dividends at regular tax rates option for metr boxplot. 

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/B-Tax#160]
![image](https://cloud.githubusercontent.com/assets/8301092/25762257/0e38e65c-31ac-11e7-8903-92b2f6cb32b8.png)

Would be cool to add an option to the [box plot](http://www.ospc.org/gallery/metr_boxplot/) to allow users to tax CG and dividends at regular income tax rates. Fancy version would also have an option for taxing CG as accrual vs realized. 

This would allow for stylized versions of [Toder/Viard](https://www.taxpolicycenter.org/sites/default/files/alfresco/publication-pdfs/2000817-a-proposal-to-reform-the-taxation-of-corporate-income.pdf) and [Lee](http://thefederalist.com/2017/01/23/congress-trump-can-reform-taxes-put-america-first/)

**Comment by codykallen** [comment]
@MattHJensen, I'm not sure how reasonable this is for online tool, but in B-Tax it can easily be done by applying `iit_reform = {start_year: {'_CG_nodiff': [True]}}`. Note that in B-Tax, capital gains tax rates are already adjusted to be accrual-effective (in parameters.py). Applying the Toder-Viard reform would require changing the hard-coded equations in parameters.py. A B-Tax user could make this change reasonably easily by changing the number of years holding stocks subject to short-term and long-term capital gains taxes (`Y_scg` and `Y_lcg`).

**Comment by jdebacker** [comment]
Closing this issue as the METR box plot is not a feature of B-Tax (it was just created with B-Tax output).  But this could be an issue for the [plots](https://github.com/open-source-economics/plots) repo.
