### ISSUE TITLE
Question about B-Tax release 0.1.7

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/B-Tax#168]
The comment on B-Tax release 0.1.7 says
```
This release has been tested to work with Tax-Calculator 0.9.0
```
If that is the case, then why not pin to taxcalc 0.9.0 until you know B-Tax works with a more recent taxcalc release?

You could do this by changing in both places the `conda.recipe/meta.yaml` file to include:
```
    - taxcalc ==0.9.0
```
instead of the current
```
    - taxcalc
```

@jdebacker @rickecon @MattHJensen @PeterDSteinberg @jbcrail

**Comment by PeterDSteinberg** [comment]
Agreed - B-Tax should be pinned to Tax-Calculator with a `>=X.Y.Z`.  It was my impression that this was being done by the `build_release.sh` script I wrote in [policybrain-builder](https://github.com/open-source-economics/policybrain-builder).  Checking the files at [https://anaconda.org/ospc/btax/files](https://anaconda.org/ospc/btax/files) it is clear that @martinholmer is right - B-Tax is not getting pinned as expected.  @jbcrail Can you make an issue in `policybrain-builder` and assign to yourself, linking back to this issue.  Thanks!

**Comment by martinholmer** [comment]
@PeterDSteinberg said:
> Agreed - B-Tax should be pinned to Tax-Calculator with a >=X.Y.Z. It was my impression that this was being done by the build_release.sh script I wrote in policybrain-builder. Checking the files at https://anaconda.org/ospc/btax/files it is clear that @martinholmer is right - B-Tax is not getting pinned as expected. @jbcrail Can you make an issue in policybrain-builder and assign to yourself, linking back to this issue. Thanks!

I don't think doing the pinning in the policybrain-builder script is the right way to proceed.

The reason is that in my view that the policybrain-builder script needs major changes in its architecture given the release process envisioned by @MattHJensen.  The script should be changed so that it operates on only one repo at a time and never changes the repo's `conda.recipe/meta.ymal` contents.  My general view is [here](https://github.com/OpenSourcePolicyCenter/webapp-public/issues/560#issuecomment-313446963).

@jbcrail

**Comment by MattHJensen** [comment]
> I don't think doing the pinning in the policybrain-builder script is the right way to proceed.

I am in agreement with @martinholmer. I think the contributors to this project should adjust the pins via PRs to this project. 

This places the ultimate responsibility for managing dependencies on the core maintainer of this project rather than the maintainers of policybrain-builder. 

@PeterDSteinberg @jbcrail

**Comment by martinholmer** [comment]
The discussion in B-Tax issue #168 seems to have reached the conclusion that the B-Tax conda.recipe/meta.yaml` specification of the taxcalc dependency should be done manually by the B-Tax developers as their tests show B-Tax works with a new version of the taxcalc package. 

So, for example, after testing B-Tax with taxcalc 0.9.1 and finding all is good, the B-Tax developers would make the following changes on two lines in `meta.yaml` and then commit those changes.  Each of the old lines would have been:
```
    - taxcalc ==0.9.0
```
and the new lines would, in this example, would be as follows:
```
    - taxcalc ==0.9.1
```

Given that this discussion seems to have run its course, this issue should be closed.

@jdebacker @MattHJensen @PeterDSteinberg @jbcrail
