### ISSUE TITLE
EATR

### ISSUE THREAD

**Issue by codykallen** [open-source-economics/B-Tax#174]
A useful addition to B-Tax would be the ability to estimate the effective average tax rate. I recommend using the [Devereux-Griffith](https://link.springer.com/article/10.1023/A:1023364421914) EATR. This can be estimated by using equations (10), (11) and (13), or with equations (14) and (15). Note that B-Tax already calculates the intermediate variables as part of estimating the METR and METTR. The only missing input for estimating these EATRs is the financial return (p in Devereux-Griffith), which can be broken down into the cost of capital and the supernormal return. 

I would suggest either assuming a general financial return under current law, or assuming different financial returns for each major asset type and entity type. The general approach applied in many papers is to estimate the supernormal share of the total return or the share of the corporate tax base attributable to the supernormal return. For background, see [Power & Frerick (2016)](https://www.treasury.gov/resource-center/tax-policy/tax-analysis/Documents/WP-111.pdf) and [Cronin et al (2013)](https://www.ntanet.org/NTJ/66/1/ntj-v66n01p239-62-distributing-corporate-income-tax.pdf). 

Again, since the intermediate variables necessary for the EATR calculations are already computed for the EMTR, I believe we could add the EATR calculation without much trouble. 

@MattHJensen @jdebacker @hdoupe

**Comment by jdebacker** [comment]
This would be a very, very nice addition to B-Tax.

> Note that B-Tax already calculates the intermediate variables as part of estimating the METR and METTR.

This is not quite right.  The Devereux-Griffith EATR model is a discrete-time model, whereas the METR model used for B-Tax is a continuous time model.  This is where I've been held up in making these additions thus far - I haven't tried to write the EATR model in continuous time so that we could use the current B-Tax function to compute the EATR in addition to the METRs.  That said, adding some discrete time version of the relevant functions would not be difficult and the heavy lifting (all the data munging to get assets splits by type/industry/tax treatment) can certainly be directly applied to the EATR calculations.

> I would suggest either assuming a general financial return under current law, or assuming different financial returns for each major asset type and entity type. The general approach applied in many papers is to estimate the supernormal share of the total return or the share of the corporate tax base attributable to the supernormal return. For background, see Power & Frerick (2016) and Cronin et al (2013).

This sounds like a fine approach to me.  Although this would be a nice place for some visualizations where one can view the results over a range of "p".

**Comment by codykallen** [comment]
> The Devereux-Griffith EATR model is a discrete time model, whereas the METR model used for B-Tax is a continuous time model. This is where I've been held up in making these additions thus far - I haven't tried to write the EATR model in continuous time so that we could use the current B-Tax function to compute the EATR in addition to the METRs. 

Actually, I think we could easily use equations (14) and (15) in Devereux-Griffith to estimate the EATR, because the only continuous-time conversion is reasonably simple for these equations (without redoing their entire derivation).

**Comment by jdebacker** [comment]
@codykallen That's great if you can make the conversion for the D-G equations to be consistent with the continuous time B-Tax calculations.  I hadn't thought to hard about this, but thought it could be trickier than given how D-G derive there model.

**Comment by jdebacker** [comment]
@codykallen has made the discrete to continuous time mapping so we can compute the EATRs using many of the computations we are already doing with B-Tax.  

A few things we might think about as we add these in:
1. Do we want the EATR in the same data frames as the METRs?  I think yes, but note that I don't know much about interactions with CCC if there are any issues passing data frames out of B-Tax with columns that aren't used in CCC (e.g., I would like to pass the economic depreciation rates but currently drop those from the B-Tax output because it had caused issues with CCC in the past).
2. B-Tax could use some reorganization.  The most natural place to add the main EATR calculations would be to `calc_final_outputs.py` (since many of the inputs to the EATR are already computed in `calc_z.py` or `parameters.py`).  But `calc_final_outputs.py` is already a bit overwhelming.  Something to think about is taking the time with these additions to reorganize the code a bit.  Would it make sense to define some classes here?  E.g., the data frame by asset could be a class with attributes such as "cost of capital", "METR" "EATR", etc.  Methods for the class would compute these attributes...

**Comment by MattHJensen** [comment]
> I think yes, but note that I don't know much about interactions with CCC if there are any issues passing data frames out of B-Tax with columns that aren't used in CCC

Does this imply that you don't think the EATRs should be on CCC? I would think they should be an option along other outputs, but maybe I'm misunderstanding your point

**Comment by jdebacker** [comment]
@MattHJensen I think they should be on CCC.  But I wasn't sure if we want pass separate data frames for METRs and EATRs or just have them in one dataframe.  

But I do think that before we add EATRs to the CCC output tables/visuals, we should think more about the best way to display.  We already have a lot going on and we have talked about adding the user cost of capital too.  

In addition, I think EATRs might deserve a different presentation than what we have for METRs.  In particular, I think we want users to be able to view the EATRs over a range of different economic profits.  And in this case, I think a visual would be ideal for the default presentation.

**Comment by MattHJensen** [comment]
> But I do think that before we add EATRs to the CCC output tables/visuals, we should think more about the best way to display. We already have a lot going on and we have talked about adding the user cost of capital too.

> In addition, I think EATRs might deserve a different presentation than what we have for METRs. In particular, I think we want users to be able to view the EATRs over a range of different economic profits. And in this case, I think a visual would be ideal for the default presentation.

PolicyBrain contributors have a lot of demands on their time right now, and tax reform is happening now, so my preference would be to start off with whatever is simplest and easiest to execute. I would think that that is adding EATR and user cost as options to the existing menu and adding economic profits to the existing list of economic baseline variables, but I could be wrong. 

![image](https://user-images.githubusercontent.com/8301092/31528320-9629ce9c-afa0-11e7-83ba-db1a6a73effa.png)

![image](https://user-images.githubusercontent.com/8301092/31528365-d91324e2-afa0-11e7-8f21-dd0bf8675972.png)

And I actually don't think that adding items to an existing menu structure adds much complexity. We added more complexity, for example, when we added a separate menu for the chart.

I agree that adding some charting capabilities could be useful as well for EATR, but I'm trying to think about what incremental steps we can take to meet existing demands most quickly and with the lowest effort from both B-Tax and PB contributors.

**Comment by jdebacker** [comment]
It seems like there are large fixed costs (e.g. lots of testing) for any PB change - hence my suggestion to take a step back to think about this before throwing up more info without thinking about the user perspective.  But, in general, I think simple is preferable (though I don't share your optimism with respect to tax reform - I think this is going to go on for a while).  

w.r.t. adding user cost as another item to the list of output radio buttons, I think we should do this.

But, EATRs depending critically on the rate of economic profits to the firms.  I guess Cody has a better idea, but I don't think we know these well in general and I think many users would like to be able to know how the EATR affects them (with whatever profit rate they think they'll have).  So my thought was that the EATRs would be most useful presented over a range of profit rates.  This would be a entirely different table than the template now.  If you agree, all I'm saying is let's discuss what that should look like.

@codykallen As a first idea, perhaps we present EATRs in tables with rows representing assets/industry (like METR tables), columns grouped by type of financing and say 3 columns for different rates of profits?  We'll want to iron this out before we think about how to add this functionality to B-Tax.

**Comment by codykallen** [comment]
I agree with the idea of several tables using different of profits. However, that raises some potential issues for structuring the financial return. In the derivation, `p` is the financial return, `rho` is the cost of capital, and `p - rho` is the supernormal return. If we think about this as the EATR on a project (with a given financial return), then a firm with a low cost of capital will have a higher supernormal return, and a firm with a high cost of capital will have a lower supernormal return. 

Alternatively, you could specify the supernormal return `s` as the input, and determine the financial return as `p = rho + s`. This form would also avoid any errors resulting from users inputting financial returns less than the cost of capital (in which case the project wouldn't be done, and the EATR is meaningless). 

Regarding actual supernormal returns, there isn't a lot of empirical evidence we can rely on for this. There are a few estimates for specific industries, but that isn't well applicable to B-Tax. I think the best recent work can be found here: https://www.treasury.gov/resource-center/tax-policy/tax-analysis/Documents/WP-111.pdf

**Comment by MattHJensen** [comment]
Regarding EATRs, @jdebacker said:

> This would be a entirely different table than the template now. If you agree, all I'm saying is let's discuss what that should look like.

This is where we disagree. I don't see full-time OSPC staff having the bandwidth to add an entirely new table to policybrain in the next 3-6 months. Therefore, I'd like to discuss how we can make EATRs available in the existing table.  If you know of other contributors who will be making these contributions in a shorter time horizon than that, then perhaps it would make sense to add a new table now, but even then it's not so clear to me that an additional table is advantageous, but it is certainly worth discussing if you know who is going to be adding it. 

I also want the user to be able to see how the results vary under alternative financial or supernormal returns, just as I think users should be able to see how the results vary under alternative nominal interest rates and inflation rates. Therefore, I think we should add a single supernormal return parameter to the macroeconomic variables section on the CCC input page and add a new output option for EATRs to the existing table on the CCC output page. 

This would allow users to vary the supernormal return at will. If the user wants to see the EATR for a particular industry, she could run CCC with the supernormal return that she thinks is relevant for that industry. If she wants an economy-wide EATR, she could use an economy-wide supernormal return. 

While tax reform may not be implemented in the next 3-6 months, the tax reform discussion is happening now.

**Comment by jdebacker** [comment]
Thanks to @codykallen for his work deriving the continuation time analogue to the EATR.  With PR #198 This is now part of the B-Tax output.
