### ISSUE TITLE
user cost available for CCC

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/B-Tax#176]
It would be valuable for CCC users to be able to display user cost of capital as well as cost of capital. (cost of capital - economic depreciation rate), so that they can apply user cost elasticities to the CCC output. 

![image](https://user-images.githubusercontent.com/8301092/31395193-2de2e27c-adae-11e7-8ae1-dcb913e4a40e.png)

Does anything need to happen in B-Tax for that to be easy for the policybrain team to add?

@jdebacker

**Comment by jdebacker** [comment]
@MattHJensen This will require a change in B-Tax.

**Comment by jdebacker** [comment]
UCC added to output variables in B-Tax with PR #194
