### ISSUE TITLE
General issues with B-Tax

### ISSUE THREAD

**Issue by codykallen** [open-source-economics/B-Tax#178]
I've encountered a handful of issues with B-Tax, and I think it would be useful to make a number of improvements based on these. Some of these general improvements come from suggestions from outside people interested in the model. I've also been building a corporate tax mode, and I would like to use B-Tax to apply an investment response using the user cost of capital (`rho + delta`). But to do this reliably, I would need a number of changes. I will list out the problems I've encountered, as well as some potential solutions. I'll start with the general ones for users, and move onto the ones more specific to my project.

**General B-Tax issues**
- [ ] 1. METR_nc and METTR_nc are not equal in the presence of debt financing. 

B-Tax sets the `METR_nc*` and `METTR_nc*` variables equal to each other. Although these are equal for equity financing, this decision creates the result that a cash flow tax has non-zero values for `METR_nc` and `METR_nc_d`. 

_Note: Continued in #179 

- [ ] 2. Debatable incorrect determination of `s_nc_e`

The determination of `s_nc_e` is based on the equilibrium assumption that the after-tax return to savers from investing in corporate equity is the same as the after-tax return to savers from investing in non-corporate equity. In the baseline, this assumption for `s_nc_e` is fine. But suppose that you reduce the tax rate on capital gains. This does not change `E_c` (which is hardcoded), so it does not affect the cost of capital for C corporations. But this policy change would raise the after-tax return to investors in corporate equity. Because of the way parameters.py is structured, this also increases `s_nc_e` and `E_nc`, even though this policy change does not directly affect pass-through incentives. Therefore, according to B-Tax, reducing the tax rate on capital gains does not affect the cost of capital for C corporations and raises the cost of capital for non-corporations. 

Note that this would be fine if a user is interested in comparing the `METR`, `METTR` and `rho` in the baseline equilibrium compared to the reform equilibrium. But if a user wants to look at the effect of a tax reform on incentives to invest at the margin, then the results for non-corporations are wrong. We discussed this previously in #177. 

I think the solution to this would require calculating `s_nc_e` and setting that value along with `E_c`. That would presumably resolve the issue, although it would need to be updated whenever Tax-Calculator changes enough to affect the basic results. 

_Note: Also discussed in #177 and #180_

- [ ] 3. Too much use of hard-coded values

I don't like that `E_c` and `E_nc` are unaffected by changes in interest rates. I think parameters.py and btax_defaults.json could use serious reorganization, to move the many hard-coded parameters in parameters.py to user-controllable parameters. This would have a number of uses. For example, interest rates are predicted to rise in the coming years. Thus a user should be allowed to move `i`, `E_c` and `E_nc` together, but currently they can only change `i`. 

_Note: Also discussed in #181_

**Economic theory issues**

- [ ] 4. Discount rate, after-tax rate of return, and interest deductibility

The current version of B-Tax uses the discount rate `r` and the after-tax rate of return `r'`, where `r'` is the weighted average of the required returns on debt and equity and `r` is the WACC, which includes interest deductibility. You use the equations
`rho = (1 - uz) / (1 - u) * (r - pi + delta) - delta`
and
`METR = (rho - (r' - pi)) / rho`

However, I think the decision to use the discount rate limits the capability of the model, constitutes a serious concern when considering implementing the EATRs mentioned in #174, and is invalid if tax rates are not constant. Personally, I prefer the equations
`rho = (1 - uz - uf) / (1 - u) * (r' - pi + delta) - delta`
and
`METR = (rho - (r' - pi)) / rho`

Note that the current method is not incorrect, and that the disagreement in this case is over the assumptions involved. 

_Note: Also discussed in #182_

**New capabilities needed** (for me and for others)

- [ ] 5. Non-constant corporate tax rates. 

The biggest complaint I've heard from users is that the business tax rates have to be constant, but this isn't realistic. It prevents us from modeling phased-in rate changes, or what happens if the tax rate increases beyond the budget window. This is a serious limitation; in the presence of anticipated tax rate changes, all of the `METR`, `METTR` and `rho` calculations are incorrect. Moreover, the calculation of `r` would also be incorrect, since it is a function of the tax rate (as long as interest is at least partially deductible). This is the main reason I want to separate out the tax savings due to interest deductibility from the discount rate. 

If the tax rate is not constant, the equations involved get significantly messier, too messy to write here (although I can send around a write-up). But the real problem arises when dealing with the present value of the tax savings from depreciation, which is no longer `uz`, especially when dealing with declining balance depreciation. One would need to break up the two integrations (over the declining balance period and the straight-line period) into integrations over periods with constant tax rates and constant antiderivates. This would require a lot of conditional statements to deal with properly, and it could get messy quickly. An alternative would be to integrate separately for each year to calculate the nominal depreciation deduction in each year (40 years for the longest lived assets), multiply by the tax rate in each year, discount these back to the present using the nominal discount rate (or after-tax rate of return), and sum. This method would be approximately correct, although not perfectly so. 

For my corporate tax model, I've already built the capability to produce the nominal depreciation deductions in each year for each type of capital cost recovery method, so we could potentially use that. 

_Note: Also discussed in #183_

- [x] 6. Separate the interest deductibility haircut into a haircut for corporations and for non-corporations. 

Given that the Tax Cuts and Jobs Act changes the treatment of interest paid for C corporations but not for pass-throughs, this is probably necessary (even though the TCJA applies a cap on interest deductibility to 30% of adjusted taxable income, rather than as a true haircut). 

_Note: Also discussed in #184_

**Comment by codykallen** [comment]
@jdebacker @MattHJensen @andersonfrailey @hdoupe

**Comment by jdebacker** [comment]
@codykallen These are all good issues to consider.  Would you mind separating into multiple issues on GitHub? This will help us check off each individually as we get to work on them.

**Comment by codykallen** [comment]
Per @jdebacker's suggestions, I have split this issue into #179, #180, #181, #182, #183, and #184.

**Comment by hdoupe** [comment]
@codykallen it may be easier to keep track of the progress on these issues if you add some checkboxes (`- [ ] `) and we check them off as we resolve these issues.

**Comment by hdoupe** [comment]
Thanks @codykallen

**Comment by codykallen** [comment]
Of these problems, numbers 4 and 5 are no longer a concern for me, and I don't think others are particularly worried about them. Problems 3 and 6 should still be addressed for usability, and problems 1 and 2 merit further consideration for the accuracy of the model.

**Comment by jdebacker** [comment]
Closing this issue.  #2, 3, 4, 5 are important to think about and remain open as separate issues.  

#6 has been addressed through a PR.

#1 was debated without strong preference to change model assumptions at the present time.
