### ISSUE TITLE
Separate the interest deductibility haircut into a haircut for corporations and for non-corporations.

### ISSUE THREAD

**Issue by codykallen** [open-source-economics/B-Tax#184]
Given that the Tax Cuts and Jobs Act changes the treatment of interest paid for C corporations but not for pass-throughs, this is probably necessary (even though the TCJA applies a cap on interest deductibility to 30% of adjusted taxable income, rather than as a true haircut).

**Comment by codykallen** [comment]
Although potentially useful, this is no longer required for my work. If you think it worthwhile, I can leave it open. If not, I'll close it.

**Comment by jdebacker** [comment]
This issue has been addressed with PR #204
