### ISSUE TITLE
Running B-Tax beyond 2020

### ISSUE THREAD

**Issue by codykallen** [open-source-economics/B-Tax#185]
Currently, running B-Tax only runs for `start_year <= 2020`. This is because the default parameters in btax_defaults.json only extend through 2020. It would be useful to at least be able to run beyond 2020. I see several ways to approach this. 
1. Extend the parameters in btax_defaults.json for additional years. 
2. Add code to pull either last entry from the parameter value lists if the year exceeds 2020. 
3. If `start_year > 2020`, set `start_year` to 2020 and issue a warning that B-Tax will run using the 2020 parameter values. 

Of these options, I prefer the third. Does anyone have a particular preference for which to use, or a different suggestion?

@jdebacker @andersonfrailey @hdoupe @MattHJensen

**Comment by codykallen** [comment]
Through work on BRC, I no longer require this capability for my own work. However, this could be a useful improvement to the existing model, especially if a tax bill creates anticipated changes to bonus depreciation beyond 2020.

**Comment by jdebacker** [comment]
Issues addressed with PR #190, which extends default parameter values through 2028.
