### ISSUE TITLE
Where on CCC website does it explain what the size of the bubbles mean?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/B-Tax#186]
When first looking at the "bubble plot" on the results page of the CCC, I didn't see where the meaning of the size of the bubble was explained.  Did I miss the explanation?  What does the size of the bubble mean?

**Comment by jdebacker** [comment]
@martinholmer You didn't miss something, it should be in the labels for the CCC plots (it's the size of assets of that type/in that industry).  This should be a PolicyBrain issue, so I'll move it over there.
