### ISSUE TITLE
B-Tax with CPS

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/B-Tax#188]
Allow an option to run B-Tax with the CPS file (i.e., the calc to tax-calc will specify the use of the CPS file).

**Comment by MattHJensen** [comment]
This is related to https://github.com/open-source-economics/taxdata/issues/119

**Comment by jdebacker** [comment]
PR #206 specifies the CPS data as test data.  

This issue will remain open until we have an option to specify the data source when running B-Tax.

**Comment by jdebacker** [comment]
Addressed in PR #209, though adjustments will be made when TaxData does an imputation of short and long term capital gains.
