### ISSUE TITLE
Can this project upgrade to Python 3.6?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/B-Tax#205]
The Pandas developers seem to be planning to quit supporting Python 2.7 at the end of 2018 as described [here](https://github.com/pandas-dev/pandas/issues/18894).  In the coming months the Tax-Calculator developers would like to transition Tax-Calculator to be a Python 3.6+ project.

**Will this project find it acceptable to have access to only Python 3.6 taxcalc packages?**

**Comment by jdebacker** [comment]
Yes.  B-Tax is currently running and tested on 3.6.

**Comment by martinholmer** [comment]
@jdebacker said:
> Yes. B-Tax is currently running and tested on 3.6.

Good.  So this is a non-issue for B-Tax.
