### ISSUE TITLE
Error with run_example

### ISSUE THREAD

**Issue by rkasher** [open-source-economics/B-Tax#214]
I ran B-Tax from master with Tax-Calculator 0.21.0 and I had the following error. 
```
ValueError: ERROR: 2018 _DependentCredit_before_CTC value 0.0 is not boolean

```
The file used for the example run `2017_law.json` needs to be updated to reflect changes in Tax-Calculator.

**Comment by jdebacker** [comment]
The `2017_law.json` has been updated to work with TC 0.22.1.  The `environment.yml` file has also been updated to pin to a more recent version of TC.
