### ISSUE TITLE
Fixing discrepancies in model output

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/B-Tax#219]
@martinholmer points out:

> The B-Tax README lists only six output files. So, I don't understand what the asset_data.pkl file contains. Also, the README says one of the output files should be base_byindustry.csv, but I got baseline_byindustry.csv; seems like it is an easy fix to drop the "line" from that output file's name. And my final question is why is the btax_output_dir created when nothing is written to that directory? Seems like that should be eliminated or the six output files should be written to that subdirectory; one or the other.

These should be corrected.

- [x] Update README to note the creation of `asset_data.pkl`
- [x] Change the name of the baseline by industry results csv file to `base_byindustry.csv`
- [x] Remove commands to create the `btax_output_dir` directory

**Comment by martinholmer** [comment]
@jdebacker said in B-Tax issue #219:
> Change the name of the baseline by industry results csv file to `baseline_byindustry.csv`

But it already has that name.  If you want both the "baseline" results files to start with "baseline", then you need to do this:
```
Change the name of the baseline by asset results csv file to baseline_byasset.csv
```
I'm have no view on what the file names should be other than most users would expect them to be consistent.

**Comment by jdebacker** [comment]
Edited typo in description about to address @martinholmer 's comment.

**Comment by jdebacker** [comment]
The `btax_output_dir` creation was removed back in PR #207.

Decided to go with `baseline_by*.csv` and updated the README appropriately.

**Comment by jdebacker** [comment]
PR #220 resolves these issues.
