### ISSUE TITLE
Stray references to the Anaconda Cloud channel ospc

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/B-Tax#227]
@jdebacker,  Thanks for all your cooperation in changing the code in the B-Tax repository so that it meets the PSLmodels Package-Builder criteria for conda package building.  I'm going the write down these criteria in a new `Package-Builder/README.md` file.  Once I've done that, you'll be able to create packages for future B-Tax releases without asking me for assistance.

Meanwhile, there are a couple of easy changes you can make now to the avoid problems in the near future when AEI will "repossess" the `ospc` channel on the Anaconda Cloud.  Soon there will be no PSLmodels packages on the `ospc` channel; they will all be on the `PSLmodels` channel.  Doing a recursive grep for `ospc` on the B-Tax source code found two problems that need fixing.  Here is the grep command and its results:
```
iMac:B-Tax-0.2.6 mrh$ grep -rin --include="*" ospc . | grep -v format_output | grep -v ospc.org
./environment.yml:3:- ospc
./.travis.yml:20:  - conda install -c ospc taxcalc
iMac:B-Tax-0.2.6 mrh$ 
```
To avoid problems in the future, simply change `ospc` to `PSLmodels` in both those files.

Let me know if you have any questions.  And thanks, again, for being so helpful in assisting me to develop the PSLmodels Package-Builder.

@MattHJensen @rickecon

**Comment by jdebacker** [comment]
These references were removed in PR #228.
