### ISSUE TITLE
Create Travis CI test

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/B-Tax#24]
Create Travis CI test. We know calculations for z, rho, metr, mettr correct.  We need to create a pickle file with objects containing these outputs so that we can check future code revisions continue to produce accurate results.

**Comment by talumbau** [comment]
@jdebacker is this resolved?

**Comment by jdebacker** [comment]
No.  We have  test to ensure (1) that all changes in input parameters produce changes in output (2) that output tables contain the correct number of columns.

But I think we need some test to say if output differs from the prior version.  Like the OG-USA regression testing, we need a manual override a failed test in the case it should differ given model changes, but we at least need to have some way to easily check for this.

**Comment by jdebacker** [comment]
We do have Travis CI working.  Will need additional unit and regression tests, but those needs are addressed in separate issues.
