### ISSUE TITLE
Partnership allocations by partner type

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/B-Tax#39]
The methodology outlined in the METR_Guide missed this footnote in the IRS spreadsheets:

> [1] Total income (loss) minus total deductions available for allocation does not equal income (loss) allocated to partners by type of partner because not all partnerships report their allocations.

The methodology to allocation assets across type of partners needs to be updated to reflect this.  Our current methodology relied on these items adding up and thus has thrown off our total amount of assets attributed to different tax entity types.

**Comment by jdebacker** [comment]
@bfgard , if you have some time, would you mind looking at pull_soi_partner.py and updating it so that is can read in the 13pa05.xlsx file?  If you can get this in there, I can help with crosswalk and with adjusting the commented out code to attribute assets across partner types.

**Comment by bfgard** [comment]
@jdebacker I'm looking at line 156 of pull_soi_partner.py and I believe that should do the job. Let me know if what's in df05 works for you.

**Comment by jdebacker** [comment]
@bfgard - totally missed that!  Thanks.  I've got to switch to something else, so feel free to try to implement that commented out code if you find time.  Else I'll get on it when I can.

**Comment by bfgard** [comment]
@jdebacker So I've updated the pull_soi_partner.py script to add back the functionality that was there previously. I didn't know if you wanted to make changes to that.

You can find the changes on my repo under the partners branch. You had it printing out a csv file, TestDF2.csv, which is also on the branch under the btax folder.

**Comment by jdebacker** [comment]
@bfgard thanks.  I'll try to take a look at this soon - I would like to add that functionality in.  It might be good to add and option to give more detailed information about the percentages of assets owned by industry and tax treatment to compare to CBO's tables.  As I look into things more, I get worried that something is still not quite right in how assets are attributed for all industries.  And there is lots of room for error with the various datasets measured at different levels of detail and measuring assets in different units.

**Comment by jdebacker** [comment]
@bfgard I was able to use your code to get started.  I've now got assets allocated across different partner types.  I'll open a PR soon - just running tests of the asset allocations across industry and tax treatment (to see if in line with CBO).

**Comment by jdebacker** [comment]
Fixed via PR #99.  Note that use slightly different methodology that CBO (2007).  Neither are perfect and 2013 partner data makes the CBO method difficult due to SOI data not summing to control totals when looking at distributions of business income by partner type.
