### ISSUE TITLE
Integration of B-Tax with TaxBrain

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/B-Tax#43]
In OpenSourcePolicyCenter/webapp-public [Issue #295](https://github.com/OpenSourcePolicyCenter/webapp-public/issues/295#issuecomment-239256270) @MattHJensen asks:

> Which parameters from the TaxBrain input page do you think would be relevant?

Those affecting marginal tax rates on business income, capital gains income, dividend income, and interest income could all be relevant.  Perhaps some other fields.  But we wouldn't take directly those values entered into TaxBrain, since B-Tax will look only at how the "marginal investor" is affected.

Given the field available from the Tax-Calculator (using the PUF-CPS data), maybe the thing to do is to compute the following:

-     tau_businc  = weighted average marginal tax rate on ordinary, non-corpororate business income (weighted by amount of non-corp business income)
-     tau_div = weighted average marginal tax rate on dividend income (weighted by amount of dividend income received)
-     tau_int = weighted average of marginal tax rate on interest income (weighted by amount of interest income received)
-     tau_scg = weighted average of marginal tax rate on short term capital gains (weighted by amount of short term capital gains received)
-     tau_lcg = weighted average of marginal tax rate on long term capital gains (weighted by amount of long term capital gains received)
-     tau_xcg = weighted average of marginal tax rate on capital gains held until death (weighted by amount of total capital gains received)
-     tau_td = weighted average of marginal tax rate on pension distributions (weighted by the amount of pension distributions)
-     tau_h = weighted average marginal tax rate on mortgage interest and property taxes (weighted by amounts of these deductions)

@MattHJensen @feenberg

**Comment by MattHJensen** [comment]
@jdebacker, due to the complex relations between ordinary income and other types of income, I expect that every single TC parameter could end up affecting at least one of the MTRs listed above. Therefore, I think every TC parameter is probably relevant to B-Tax. Is that your assessment as well?

**Comment by jdebacker** [comment]
Yes.  Although, so we should give option to user to potentially specify any of those inputs to TaxBrain.

**Comment by MattHJensen** [comment]
Posted a response back over at #295. Outstanding question is what the simplified set of parameters will contain:

> But we might consider a more simplified set of parameters that show up on the B-Tax input page

**Comment by jdebacker** [comment]
Closing.  Tax Calculator has been integrated into B-Tax for some time now.  Relevant issue is now [Issue #357](https://github.com/OpenSourcePolicyCenter/webapp-public/issues/357) in web app repo, discussing allowing use of this integration by CCC users.
