### ISSUE TITLE
Add "divisor" and "decimals" to btax/param_defaults/btax_results_by*.json

### ISSUE THREAD

**Issue by PeterDSteinberg** [open-source-economics/B-Tax#47]
To help with table formatting, we can specify a `"units"`, `"divisor"` and `"decimals"` for each of the column metadata dictionaries in `btax/param_defaults/btax_results_by*.json`.  Setting `divisor` to 1000 and decimals to 0 would round off to the 1000s with no left over.

**Comment by jdebacker** [comment]
@PeterDSteinberg , I can do this.  Let me clarify a couple things:

1. If I want the tables to display to 3 decimal places, do I set "decimals=3"?
2. Are units going to be column labels?  Everything is in terms of rates, so these are probably unnecessary and the table title should cover it.

**Comment by PeterDSteinberg** [comment]
@jdebacker Yes, setting `decimals` is the number of digits after the decimal.  If you want to show numbers with thousandths, then set `divisor` to 1 and `decimals` to 3.  

We can skip `units` if covered by the titles already there.

**Comment by jdebacker** [comment]
Added in PR #48
