### ISSUE TITLE
We need conda packages for `btax`

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/B-Tax#57]
These should live on the OSPC channel on anaconda.org: [anaconda.org/ospc](http://www.anaconda.org/ospc). There should at least be {Linux, Mac, Win64} X {Python 2.7}.

**Comment by PeterDSteinberg** [comment]
Fixed by [policybrain-builder](https://github.com/open-source-economics/policybrain-builder) - made new packages yesterday.

**Comment by jdebacker** [comment]
As @PeterDSteinberg points out, this issue has been addressed.  Thanks for the work!
