### ISSUE TITLE
Use more "raw" data

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/B-Tax#68]
Try to use only files as formatted from their respective sources (e.g. SOI, BEA, Financial Accounts).  Currently, we do some reformatting of these files manually since they are difficult to read into a data frame.  It would be ideal to be able to drop in new vintages of files without the additional effort.

**Comment by jdebacker** [comment]
@bfgard , was this fixed in PR #80?

**Comment by bfgard** [comment]
Yes it was

**Comment by jdebacker** [comment]
@bfgard thanks.  Closed via PR #80
