### ISSUE TITLE
Naming of runner scripts

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/B-Tax#71]
@PeterDSteinberg , would it make sense (and make things more clear) if we rename "run_btax.py" to "execute.py"?

In addition, I have a preference to rename the the following functions within run_btax:
- `run_btax` to `runner`
- `run_btax_with_baseline_delta` to `btax_with_baseline_delta`
- `run_btax_to_json_tables` to `btax_to_json_tables`

These changes follow the naming conventions used in OG-USA and also free up a script named "run_btax.py" to be the script that where one can input reforms to run locally.

Let me know your thoughts and I'll open a PR with these changes.

**Comment by PeterDSteinberg** [comment]
Those changes sound good, @jdebacker .  I apologize for missing this and other B-Tax issues until just now.

**Comment by jdebacker** [comment]
@PeterDSteinberg ok, I'll go through and make these changes after fixing tests on my outstanding PR and merging that.

**Comment by jdebacker** [comment]
Closed via PR #127
