### ISSUE TITLE
Inputting user defined reforms in B-Tax

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/B-Tax#72]
Currently, the way one inputs user defined reforms in B-Tax is with a function call like the following:

```
start_year = 2016
iit_reform = {
start_year: {
    '_II_rt5': [.3],
    '_II_rt6': [.3],
    '_II_rt7': [0.3],
}, }

run_btax(start_year,iit_reform,btax_betr_pass=0.23, btax_betr_corp=0.25, btax_depr_allyr_exp=1.,
         btax_other_hair=1.)
```

The `iit_reform` dictionary is the reform that is sent to the Tax-Calculator.  The arguments following this dictionary in the function call are changes to the policy parameters native to B-Tax.  

This issue is to discuss whether B-Tax should adopt the approach used by the Tax-Calculator in using a similar dictionary structure to input reform parameters.

I'm not sure I understand all the relevant trade-offs, but I guess we'd at least want to think about:
1) Do we want consistency across models?
2) Is one method or another more concise?
3) Is one method or another easier to understand?

cc @PeterDSteinberg @talumbau  @bfgard

**Comment by PeterDSteinberg** [comment]
I could go either way on this one, @jdebacker .  It doesn't seem terribly important to change.  If we put all the B-Tax-specific parameters into a single dict argument that might provide some clarity for the new user with B-Tax parameter adjustments like the example above with `btax_betr_pass`, but if the new user just wants to do what is now:

`run_btax(start_year, iit_reform)`

(no B-Tax params), then they would have to add a third argument being a dict with no keys/values:

`run_btax(start_year, iit_reform, {})`

**Comment by jdebacker** [comment]
@PeterDSteinberg thanks for the feedback. 

@MattHJensen I'm going to close this for now, unless you have thoughts given the push to have dictionaries of pre-pacakges reforms.  My thinking is that such reforms would benefit from putting B-Tax specific parameters into a single dictionary, but perhaps you could weigh in on this.
