### ISSUE TITLE
Conda recipe version number should come from git tag instead of hard coded

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/B-Tax#75]
We should use git keywords for expansion of version in the meta.yaml, so that the git `archive` command properly inserts the version number:

http://git-memo.readthedocs.io/en/latest/git_archive.html

**Comment by talumbau** [comment]
this is what versioneer does.

**Comment by talumbau** [comment]
this is what versioneer does.

**Comment by talumbau** [comment]
this is what versioneer does.

**Comment by brittainhard** [comment]
Looks like setup.py calls versioneer for getting versions. @PeterDSteinberg can you verify this is the case?

**Comment by jdebacker** [comment]
The version number is indeed taken from git.
